### ISSUE TITLE
`with-additional-middleware` doesn't work?

### ISSUE THREAD

**Issue by ackerleytng** [tirkarthi/clj-http-ssrf#3]
Would you happen to know why this doesn't work? I'm getting a null pointer exception. it seems as though `client/get` was executed on `nil`

```
(client/with-additional-middleware [(ssrf/wrap-validators :hosts ["192.168.0.0/16"] :status 404)] (client/get "http://www.google.com"))
```

**Comment by tirkarthi** [comment]
Thanks for reporting this. It happens due to the fact that using `with-additional-middleware` adds the `wrap-validators` to the beginning of the middleware sequence. The `wrap-request` middleware is needed to have the `url` key added to the request object. Thus `(:url req)` at https://github.com/tirkarthi/clj-http-ssrf/blob/master/src/clj_http_ssrf/core.clj#L22 returns nil instead of the url causing the exception.


You can use the below as a workaround. I will add a fix for the same.

```clojure
(client/with-middleware (conj client/default-middleware (wrap-validators :hosts ["192.168.0.0/16"] :status 404)) (client/get "http://www.google.com"))
```

Edit : `wrap-request` and not `wrap-url`

**Comment by ackerleytng** [comment]
I see, thanks! So I probably just shouldn't use `with-additional-middleware`. Thanks!
